import type { Project, Subject, Query, Activity, Notification, User, Visit, ExportConfig, CRF, LoginLog, ProjectLog, CenterLog } from '@/types'

// 项目数据
export const mockProjects: Project[] = [
  {
    id: '1',
    name: '肿瘤药物临床试验A',
    description: '一项评估X药物治疗非小细胞肺癌的疗效和安全性研究',
    status: '进行中',
    centerCount: 3,
    subjectCount: 86,
    enrolledCount: 45,
    targetCount: 100,
    createdAt: '2026-02-01',
    updatedAt: '2026-03-07',
    progress: 45,
    queryCount: 5,
    manager: '张医生',
    startDate: '2026-02-01',
    endDate: '2026-08-01',
  },
  {
    id: '2',
    name: '心血管药物试验B',
    description: '评估降压药物对原发性高血压的疗效',
    status: '审批中',
    centerCount: 2,
    subjectCount: 0,
    enrolledCount: 0,
    targetCount: 50,
    createdAt: '2026-03-01',
    updatedAt: '2026-03-01',
    progress: 0,
    queryCount: 0,
    manager: '李医生',
    startDate: '2026-03-15',
  },
  {
    id: '3',
    name: '糖尿病新药试验C',
    description: '口服降糖药物II期临床试验',
    status: '已驳回',
    centerCount: 1,
    subjectCount: 12,
    enrolledCount: 0,
    targetCount: 50,
    createdAt: '2026-01-15',
    updatedAt: '2026-02-20',
    progress: 0,
    queryCount: 2,
    manager: '王医生',
    startDate: '2026-01-15',
  },
  {
    id: '4',
    name: '阿尔茨海默病药物D',
    description: '评估药物对轻度认知障碍的改善作用',
    status: '已暂停',
    centerCount: 4,
    subjectCount: 52,
    enrolledCount: 30,
    targetCount: 80,
    createdAt: '2025-12-10',
    updatedAt: '2026-02-28',
    progress: 37.5,
    queryCount: 8,
    manager: '赵医生',
    startDate: '2025-12-10',
  },
  {
    id: '5',
    name: '康复训练研究E',
    description: '术后康复训练方案有效性研究',
    status: '已完成',
    centerCount: 2,
    subjectCount: 60,
    enrolledCount: 60,
    targetCount: 60,
    createdAt: '2025-10-01',
    updatedAt: '2026-01-15',
    progress: 100,
    queryCount: 0,
    manager: '陈医生',
    startDate: '2025-10-01',
    endDate: '2026-01-15',
  },
  {
    id: '6',
    name: '抗生素疗效评估F',
    description: '新型抗生素对耐药菌感染的治疗效果研究',
    status: '已锁库',
    centerCount: 5,
    subjectCount: 120,
    enrolledCount: 120,
    targetCount: 120,
    createdAt: '2025-08-01',
    updatedAt: '2025-12-01',
    progress: 100,
    queryCount: 0,
    manager: '刘医生',
    startDate: '2025-08-01',
    endDate: '2025-12-01',
  },
  {
    id: '7',
    name: '免疫疗法试验G',
    description: 'CAR-T细胞治疗晚期实体瘤研究',
    status: '立项中',
    centerCount: 0,
    subjectCount: 0,
    enrolledCount: 0,
    targetCount: 30,
    createdAt: '2026-03-05',
    updatedAt: '2026-03-05',
    progress: 0,
    queryCount: 0,
    manager: '孙医生',
  },
]

// 受试者数据
export const mockSubjects: Subject[] = [
  {
    id: 'S001',
    screeningId: 'SCR-2026-001',
    randomId: 'RND-001',
    name: '张三',
    gender: '男',
    age: 45,
    center: '北京协和医院',
    currentVisit: '治疗期访视2',
    enrollmentDate: '2026-02-15',
    status: '已入组',
    progress: 65,
    queryCount: 2,
    phone: '138****1234',
    email: 'zhangsan@example.com',
  },
  {
    id: 'S002',
    screeningId: 'SCR-2026-002',
    randomId: 'RND-002',
    name: '李四',
    gender: '女',
    age: 52,
    center: '北京协和医院',
    currentVisit: '治疗期访视1',
    enrollmentDate: '2026-02-20',
    status: '已入组',
    progress: 45,
    queryCount: 0,
    phone: '139****5678',
  },
  {
    id: 'S003',
    screeningId: 'SCR-2026-003',
    gender: '男',
    age: 38,
    center: '上海华山医院',
    currentVisit: '筛选期访视2',
    status: '筛选中',
    progress: 20,
    queryCount: 1,
    phone: '137****9012',
  },
  {
    id: 'S004',
    screeningId: 'SCR-2026-004',
    randomId: 'RND-003',
    name: '王五',
    gender: '女',
    age: 41,
    center: '上海华山医院',
    currentVisit: '随访期访视1',
    enrollmentDate: '2026-01-10',
    status: '完成',
    progress: 100,
    queryCount: 0,
    phone: '136****3456',
  },
  {
    id: 'S005',
    screeningId: 'SCR-2026-005',
    gender: '男',
    age: 55,
    center: '广州中山医院',
    currentVisit: '-',
    status: '脱落',
    progress: 30,
    queryCount: 3,
    phone: '135****7890',
  },
  {
    id: 'S006',
    screeningId: 'SCR-2026-006',
    gender: '女',
    age: 48,
    center: '北京协和医院',
    currentVisit: '-',
    status: '筛选失败',
    progress: 10,
    queryCount: 0,
    phone: '134****2468',
  },
  {
    id: 'S007',
    screeningId: 'SCR-2026-007',
    randomId: 'RND-004',
    name: '赵六',
    gender: '男',
    age: 50,
    center: '广州中山医院',
    currentVisit: '治疗期访视3',
    enrollmentDate: '2026-01-25',
    status: '已入组',
    progress: 85,
    queryCount: 1,
    phone: '133****1357',
  },
]

// 质疑数据
export const mockQueries: Query[] = [
  {
    id: 'Q001',
    subjectId: 'S001',
    subjectName: '张三',
    projectId: '1',
    projectName: '肿瘤药物临床试验A',
    crfName: '生命体征检查',
    fieldName: '收缩压',
    content: '收缩压值160mmHg超出正常范围，请确认是否记录正确',
    status: '待处理',
    createdAt: '2026-03-07 10:30:00',
    creator: 'DM专员',
    replies: [],
  },
  {
    id: 'Q002',
    subjectId: 'S002',
    subjectName: '李四',
    projectId: '1',
    projectName: '肿瘤药物临床试验A',
    crfName: '实验室检查',
    fieldName: '白细胞计数',
    content: '白细胞计数2.1×10^9/L低于正常范围，请核实检查结果',
    status: '处理中',
    createdAt: '2026-03-06 16:45:00',
    creator: '医学专员',
    replies: [
      {
        id: 'R001',
        content: '已联系实验室确认，结果无误',
        type: 'reply',
        createdAt: '2026-03-07 09:15:00',
        creator: '李医生',
      },
    ],
  },
  {
    id: 'Q003',
    subjectId: 'S007',
    subjectName: '赵六',
    projectId: '1',
    projectName: '肿瘤药物临床试验A',
    crfName: '不良事件记录',
    fieldName: '事件描述',
    content: '不良事件结束日期早于开始日期，请修正',
    status: '待确认',
    createdAt: '2026-03-05 14:20:00',
    creator: '数据管理员',
    replies: [
      {
        id: 'R002',
        content: '已修正，请确认',
        type: 'reply',
        createdAt: '2026-03-06 10:00:00',
        creator: '赵医生',
      },
    ],
  },
  {
    id: 'Q004',
    subjectId: 'S004',
    subjectName: '王五',
    projectId: '1',
    projectName: '肿瘤药物临床试验A',
    crfName: '合并用药记录',
    fieldName: '用药剂量',
    content: '用药剂量单位不完整，请补充mg或g',
    status: '已解决',
    createdAt: '2026-03-04 11:30:00',
    creator: 'DM专员',
    replies: [
      {
        id: 'R003',
        content: '已补充单位为mg',
        type: 'reply',
        createdAt: '2026-03-04 15:20:00',
        creator: '王五',
      },
      {
        id: 'R004',
        content: '确认无误，已关闭质疑',
        type: 'reply',
        createdAt: '2026-03-05 09:00:00',
        creator: 'DM专员',
      },
    ],
  },
  {
    id: 'Q005',
    subjectId: 'S001',
    subjectName: '张三',
    projectId: '1',
    projectName: '肿瘤药物临床试验A',
    crfName: '体格检查',
    fieldName: '体重',
    content: '体重变化超过10%，请确认是否录入正确',
    status: '已撤销',
    createdAt: '2026-03-03 09:00:00',
    creator: '数据管理员',
    replies: [],
  },
]

// 活动数据
export const mockActivities: Activity[] = [
  {
    id: 'A001',
    type: 'fill',
    content: '受试者#001 - 既往病史 已填写',
    subjectId: 'S001',
    createdAt: '2026-03-07T10:30:00',
    time: '10:30',
  },
  {
    id: 'A002',
    type: 'query',
    content: '受试者#002 - 收到1条新质疑',
    subjectId: 'S002',
    createdAt: '2026-03-07T09:15:00',
    time: '09:15',
  },
  {
    id: 'A003',
    type: 'enroll',
    content: '受试者#008 - 已完成入组',
    subjectId: 'S008',
    createdAt: '2026-03-06T16:45:00',
    time: '昨天',
  },
  {
    id: 'A004',
    type: 'complete',
    content: '受试者#004 - 完成所有访视',
    subjectId: 'S004',
    createdAt: '2026-03-06T14:20:00',
    time: '昨天',
  },
  {
    id: 'A005',
    type: 'fill',
    content: '受试者#003 - 体格检查 已填写',
    subjectId: 'S003',
    createdAt: '2026-03-05T11:30:00',
    time: '03-05',
  },
]

// 通知数据
export const mockNotifications: Notification[] = [
  {
    id: 'N001',
    type: 'info',
    title: '系统维护通知',
    content: '系统将于今晚22:00-24:00进行例行维护，请提前保存工作',
    createdAt: '2026-03-07T08:00:00',
    read: false,
  },
  {
    id: 'N002',
    type: 'warning',
    title: '项目进度提醒',
    content: '肿瘤药物临床试验A入组进度达到45%，距离目标还有55人',
    createdAt: '2026-03-06T10:00:00',
    read: false,
  },
  {
    id: 'N003',
    type: 'success',
    title: '审批通过',
    content: '您提交的新项目申请已通过审批',
    createdAt: '2026-03-05T14:30:00',
    read: true,
  },
]

// 用户数据
export const mockUsers: User[] = [
  {
    id: 'U001',
    name: '张医生',
    username: 'zhangdoctor',
    department: '肿瘤科',
    center: '北京协和医院',
    role: '研究者',
    status: '已启用',
    email: 'zhang@hospital.com',
    phone: '13800138000',
    lastLogin: '2026-03-07 08:30',
  },
  {
    id: 'U002',
    name: '李护士',
    username: 'linurse',
    department: '心内科',
    center: '上海华山医院',
    role: '研究护士',
    status: '已启用',
    email: 'li@hospital.com',
    phone: '13900139000',
    lastLogin: '2026-03-07 09:00',
  },
  {
    id: 'U003',
    name: '王专员',
    username: 'wangdm',
    department: '数据管理部',
    center: '数据管理中心',
    role: '数据管理员',
    status: '已启用',
    email: 'wang@cro.com',
    phone: '13700137000',
    lastLogin: '2026-03-06 17:00',
  },
  {
    id: 'U004',
    name: '赵医生',
    username: 'zhaodoctor',
    department: '神经内科',
    center: '北京协和医院',
    role: '研究者',
    status: '已禁用',
    email: 'zhao@hospital.com',
    phone: '13600136000',
    lastLogin: '2026-02-28 10:00',
  },
  {
    id: 'U005',
    name: '陈专员',
    username: 'chenmed',
    department: '医学部',
    center: '医学中心',
    role: '医学专员',
    status: '已启用',
    email: 'chen@cro.com',
    phone: '13500135000',
    lastLogin: '2026-03-07 10:30',
  },
]

// 访视数据
export const mockVisits: Visit[] = [
  {
    id: 'V001',
    name: '筛选期访视1',
    phase: '筛选期',
    type: '单次',
    order: 1,
    crfs: ['人口学资料', '既往病史', '体格检查'],
    windowDays: 0,
  },
  {
    id: 'V002',
    name: '筛选期访视2',
    phase: '筛选期',
    type: '单次',
    order: 2,
    crfs: ['实验室检查', '心电图'],
    windowDays: 7,
  },
  {
    id: 'V003',
    name: '治疗期访视1',
    phase: '治疗期',
    type: '单次',
    order: 3,
    crfs: ['人口学资料', '体格检查', '实验室检查'],
    windowDays: 3,
  },
  {
    id: 'V004',
    name: '治疗期访视2',
    phase: '治疗期',
    type: '循环',
    order: 4,
    crfs: ['体格检查', '实验室检查', '不良事件', '合并用药'],
    windowDays: 3,
  },
  {
    id: 'V005',
    name: '治疗期访视3',
    phase: '治疗期',
    type: '循环',
    order: 5,
    crfs: ['体格检查', '实验室检查', '不良事件', '合并用药'],
    windowDays: 3,
  },
  {
    id: 'V006',
    name: '随访期访视1',
    phase: '随访期',
    type: '单次',
    order: 6,
    crfs: ['体格检查', '实验室检查', '心电图'],
    windowDays: 7,
  },
]

// CRF 列表
export const mockCRFs = [
  '人口学资料',
  '既往病史',
  '体格检查',
  '实验室检查',
  '心电图',
  '不良事件',
  '合并用药',
]

// 访视-CRF 矩阵
export const visitCRFMatrix: Record<string, string[]> = {
  '人口学资料': ['V001', 'V003'],
  '既往病史': ['V001'],
  '体格检查': ['V001', 'V003', 'V004', 'V005', 'V006'],
  '实验室检查': ['V002', 'V003', 'V004', 'V005', 'V006'],
  '心电图': ['V002', 'V006'],
  '不良事件': ['V004', 'V005'],
  '合并用药': ['V004', 'V005'],
}

// 导出历史
export const mockExportHistory: ExportConfig[] = [
  {
    id: 'E001',
    centers: ['北京协和医院', '上海华山医院'],
    subjects: ['all'],
    crfScope: 'all',
    format: 'csv',
    includeAudit: true,
    includeModifiedOnly: false,
    includeCreator: true,
    status: 'completed',
    createdAt: '2026-03-06 15:30:00',
    fileName: '肿瘤试验A_数据导出_20260306.csv',
  },
  {
    id: 'E002',
    centers: ['全部中心'],
    subjects: ['all'],
    crfScope: 'selected',
    selectedCRFs: ['人口学资料', '体格检查'],
    format: 'pdf',
    includeAudit: false,
    includeModifiedOnly: false,
    includeCreator: false,
    status: 'completed',
    createdAt: '2026-03-05 10:00:00',
    fileName: '肿瘤试验A_CRF导出_20260305.pdf',
  },
  {
    id: 'E003',
    centers: ['广州中山医院'],
    subjects: ['all'],
    crfScope: 'all',
    format: 'sas',
    includeAudit: true,
    includeModifiedOnly: true,
    includeCreator: true,
    status: 'processing',
    createdAt: '2026-03-07 09:00:00',
    fileName: '肿瘤试验A_SAS导出_20260307.sas7bdat',
  },
]

// CRF 模板数据
export const mockCRFTemplates: CRF[] = [
  {
    id: 'T001',
    name: '人口学资料',
    code: 'DM',
    description: '记录受试者的基本人口学信息',
    isTemplate: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    sections: [
      {
        id: 'S001',
        name: '基本信息',
        order: 1,
        fields: [
          {
            id: 'F001',
            name: '姓名缩写',
            label: '姓名缩写',
            type: 'input',
            required: true,
            placeholder: '请输入姓名缩写',
          },
          {
            id: 'F002',
            name: '性别',
            label: '性别',
            type: 'radio',
            required: true,
            options: [
              { label: '男', value: 'male' },
              { label: '女', value: 'female' },
            ],
          },
          {
            id: 'F003',
            name: '出生日期',
            label: '出生日期',
            type: 'date',
            required: true,
          },
        ],
      },
    ],
  },
  {
    id: 'T002',
    name: '体格检查',
    code: 'PE',
    description: '记录受试者的体格检查结果',
    isTemplate: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    sections: [],
  },
  {
    id: 'T003',
    name: '实验室检查',
    code: 'LB',
    description: '记录受试者的实验室检查结果',
    isTemplate: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    sections: [],
  },
  {
    id: 'T004',
    name: '既往病史',
    code: 'MH',
    description: '记录受试者的既往病史',
    isTemplate: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    sections: [],
  },
  {
    id: 'T005',
    name: '不良事件',
    code: 'AE',
    description: '记录受试者的不良事件',
    isTemplate: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    sections: [],
  },
  {
    id: 'T006',
    name: '合并用药',
    code: 'CM',
    description: '记录受试者的合并用药情况',
    isTemplate: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    sections: [],
  },
]

// 登录日志数据
export const mockLoginLogs: LoginLog[] = [
  {
    id: 'L001',
    userId: 'U001',
    username: 'zhangdoctor',
    name: '张医生',
    ip: '192.168.1.100',
    browser: 'Chrome 122.0',
    os: 'Windows 11',
    loginTime: '2026-03-07 08:30:15',
    status: 'success',
  },
  {
    id: 'L002',
    userId: 'U002',
    username: 'linurse',
    name: '李护士',
    ip: '192.168.1.101',
    browser: 'Edge 121.0',
    os: 'Windows 10',
    loginTime: '2026-03-07 09:00:22',
    status: 'success',
  },
  {
    id: 'L003',
    userId: 'U003',
    username: 'wangdm',
    name: '王专员',
    ip: '10.0.0.55',
    browser: 'Chrome 122.0',
    os: 'macOS 14.3',
    loginTime: '2026-03-06 17:15:30',
    logoutTime: '2026-03-06 19:30:00',
    status: 'success',
  },
  {
    id: 'L004',
    userId: 'U005',
    username: 'chenmed',
    name: '陈专员',
    ip: '192.168.2.10',
    browser: 'Firefox 123.0',
    os: 'Windows 11',
    loginTime: '2026-03-07 10:30:00',
    status: 'success',
  },
  {
    id: 'L005',
    userId: 'U004',
    username: 'zhaodoctor',
    name: '赵医生',
    ip: '192.168.1.105',
    browser: 'Chrome 122.0',
    os: 'Windows 10',
    loginTime: '2026-03-05 14:20:00',
    status: 'failed',
    failReason: '密码错误',
  },
]

// 项目留痕数据
export const mockProjectLogs: ProjectLog[] = [
  {
    id: 'P001',
    projectId: '1',
    projectName: '肿瘤药物临床试验A',
    userId: 'U001',
    username: 'zhangdoctor',
    action: '创建项目',
    actionType: 'create',
    content: '创建了项目"肿瘤药物临床试验A"',
    createdAt: '2026-02-01 09:00:00',
  },
  {
    id: 'P002',
    projectId: '1',
    projectName: '肿瘤药物临床试验A',
    userId: 'U003',
    username: 'wangdm',
    action: '提交审核',
    actionType: 'audit',
    content: '提交了项目审核申请',
    createdAt: '2026-02-05 10:30:00',
  },
  {
    id: 'P003',
    projectId: '1',
    projectName: '肿瘤药物临床试验A',
    userId: 'U001',
    username: 'zhangdoctor',
    action: '修改项目信息',
    actionType: 'update',
    content: '修改了项目基本信息',
    oldValue: '目标入组人数: 80',
    newValue: '目标入组人数: 100',
    createdAt: '2026-02-10 14:20:00',
  },
  {
    id: 'P004',
    projectId: '1',
    projectName: '肿瘤药物临床试验A',
    userId: 'U005',
    username: 'chenmed',
    action: '数据导出',
    actionType: 'export',
    content: '导出了项目数据，格式: CSV',
    createdAt: '2026-03-06 15:30:00',
  },
  {
    id: 'P005',
    projectId: '6',
    projectName: '抗生素疗效评估F',
    userId: 'U001',
    username: 'zhangdoctor',
    action: '项目锁库',
    actionType: 'lock',
    content: '执行了项目锁库操作',
    createdAt: '2025-12-01 18:00:00',
  },
]

// 中心留痕数据
export const mockCenterLogs: CenterLog[] = [
  {
    id: 'C001',
    centerId: 'C001',
    centerName: '北京协和医院',
    userId: 'U001',
    username: 'zhangdoctor',
    action: '创建中心',
    actionType: 'create',
    content: '创建了研究中心"北京协和医院"',
    createdAt: '2026-01-15 09:00:00',
  },
  {
    id: 'C002',
    centerId: 'C001',
    centerName: '北京协和医院',
    userId: 'U003',
    username: 'wangdm',
    action: '分配用户',
    actionType: 'assign',
    content: '将张医生分配到北京协和医院',
    createdAt: '2026-01-20 10:30:00',
  },
  {
    id: 'C003',
    centerId: 'C002',
    centerName: '上海华山医院',
    userId: 'U001',
    username: 'zhangdoctor',
    action: '创建中心',
    actionType: 'create',
    content: '创建了研究中心"上海华山医院"',
    createdAt: '2026-01-16 11:00:00',
  },
  {
    id: 'C004',
    centerId: 'C001',
    centerName: '北京协和医院',
    userId: 'U003',
    username: 'wangdm',
    action: '修改中心信息',
    actionType: 'update',
    content: '更新了中心联系信息',
    createdAt: '2026-02-01 14:00:00',
  },
]
